### ISSUE TITLE
Improper abstraction of codebase

### ISSUE THREAD

**Issue by PraveenAsh** [SkalskiP/ILearnMachineLearning.js#9]
As mentioned in your Medium post, the model to import isn't hard. How to import the weights to the model?

My implementation is to be done in react vanilla javascript. So could you share the proper code flow of how the model and weights are loaded? How are reducers working to make predictions instantly?

I would highly encourage you to write another medium post just explaining the setup, configuration and the overall flow of the codebase.

**Comment by SkalskiP** [comment]
Hello! Due to the large number of duties - some time ago I temporarily suspended the work on this repository. That's why I noticed so late that you were creating an issue here. I am very sorry.

1.  "How to import the weights to the model?" - For example, if you enter the `./models/mnist/ModelJS/ `folder, you can see that in addition to the `model.json` file, there are also shards. This is where the weights of our model are located. They are loaded automatically with the models. This is because there are links to these files in `model.json`. These files must be located in the same place as `model.json`.

2. "How are reducers working to make predictions instantly?" - Redusers are part of the [Redux](https://github.com/reduxjs/redux) library. It is a library that manages the state of the JS application. It is very helpful if we want for example to refresh automatically any of the components in response to the prediction.

3. "I would highly encourage you to write another medium post just explaining the setup, configuration and the overall flow of the codebase." - You mean a post about how to create React applications using TF.js?
